name: 📂分文件夹sync
on:
    workflow_dispatch:
jobs:
    aria2:
        name: OneDrive to Onedrive Sync （📂-aria2）
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi:aria2 onedrive-backup:backup/aria2 --transfers 16 -v --ignore-errors
              
    public:
        name: OneDrive to Onedrive Sync （📂-public）
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi:public onedrive-backup:backup/public --transfers 16 -v --ignore-errors

transmission:
        name: OneDrive to Onedrive Sync （📂-transmission）
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi:transmission onedrive-backup:backup/transmission --transfers 16 -v --ignore-errors


video:
        name: OneDrive to Onedrive Sync （📂-video）
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi:video onedrive-backup:backup/video --transfers 16 -v --ignore-errors



odgd:
        name: OneDrive to Onedrive Sync （📂-）
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi: onedrive-backup:backup --transfers 48 -v --ignore-errors



odgd:
        name: OneDrive to Onedrive Sync （📂-）
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi: onedrive-backup:backup --transfers 48 -v --ignore-errors


odgd:
        name: OneDrive to Onedrive Sync （📂-）
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              rclone sync onedrive-wceshi: onedrive-backup:backup --transfers 48 -v --ignore-errors





