name: Drive Sync
on:
    workflow_dispatch:
    schedule:
        - cron: '0 2 * * 5'
jobs:
    odgd:
        name: OneDrive to Onedrive Sync
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Copy
          run: |
              # Start Mission 
              bash copy.sh

